controller_list:
  - name: fake_thumb_controller
    joints:
      - left_hand_Thumb_j1
      - left_hand_Thumb_j2
      - left_hand_Thumb_j3
  - name: fake_index_finger_controller
    joints:
      - left_hand_Index_Finger_j1
      - left_hand_Index_Finger_j2
  - name: fake_middle_finger_controller
    joints:
      - left_hand_Middle_Finger_j1
      - left_hand_Middle_Finger_j2
  - name: fake_fingers_controller
    joints:
      - left_hand_Index_Finger_j1
      - left_hand_Index_Finger_j2
      - left_hand_Middle_Finger_j1
      - left_hand_Middle_Finger_j2
      - left_hand_Pinky_Finger_j1
      - left_hand_Ring_Finger_j1
      - left_hand_Thumb_j1
      - left_hand_Thumb_j2
      - left_hand_Thumb_j3
  - name: fake_ring_finger_controller
    joints:
      - left_hand_Ring_Finger_j1
      - left_hand_Ring_Finger_j2
      - left_hand_Ring_Finger_j3
  - name: fake_pinky_finger_controller
    joints:
      - left_hand_Pinky_Finger_j1
      - left_hand_Pinky_Finger_j2
      - left_hand_Pinky_Finger_j3